version: '3.8'

services:
  # Landing Page - Desenvolvimento
  landing-page:
    build:
      context: ./LANDING-PAGE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./LANDING-PAGE:/app
      - landing_page_static:/app/staticfiles
      - landing_page_media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/landing_page
    depends_on:
      - db
      - redis
    networks:
      - saas-dev-network

  # Sistema de Reciclagem - Desenvolvimento
  recycling-system:
    build:
      context: ./sistema
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./sistema:/app
      - sistema_static:/app/staticfiles
      - sistema_media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/recycling_system
    depends_on:
      - db
      - redis
    networks:
      - saas-dev-network

  # Sistema Fiscal - Desenvolvimento
  fiscal-system:
    build:
      context: ./fiscal
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./fiscal:/app
      - fiscal_static:/app/staticfiles
      - fiscal_media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fiscal_system
    depends_on:
      - db
      - redis
    networks:
      - saas-dev-network

  # Clínica Management - Desenvolvimento
  clinica-system:
    build:
      context: ./clinica
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./clinica:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - saas-dev-network

  # Aplicação Principal - Desenvolvimento
  main-app:
    build:
      context: ./app-aviladevops
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./app-aviladevops:/app
      - main_app_static:/app/staticfiles
      - main_app_media:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/main_app
    depends_on:
      - db
      - redis
    networks:
      - saas-dev-network

  # PostgreSQL - Desenvolvimento
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=aviladevops_saas_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - saas-dev-network

  # Redis - Desenvolvimento
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - saas-dev-network

  # Nginx de desenvolvimento
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/saas.dev.conf:/etc/nginx/conf.d/default.conf
      - landing_page_static:/app/landing-page/staticfiles:ro
      - sistema_static:/app/sistema/staticfiles:ro
      - fiscal_static:/app/fiscal/staticfiles:ro
      - main_app_static:/app/main-app/staticfiles:ro
    depends_on:
      - landing-page
      - recycling-system
      - fiscal-system
      - clinica-system
      - main-app
    networks:
      - saas-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:
  landing_page_static:
  landing_page_media:
  sistema_static:
  sistema_media:
  fiscal_static:
  fiscal_media:
  main_app_static:
  main_app_media:

networks:
  saas-dev-network:
    driver: bridge
