# AlertManager Configuration for Ávila DevOps SaaS
# Alert routing, grouping, and notification configuration

global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  pagerduty_url: '${PAGERDUTY_URL}'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Alert routing
route:
  # Default receiver for all alerts
  receiver: 'default-receiver'
  
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service']
  
  # Wait time before sending first notification
  group_wait: 10s
  
  # Wait time before sending notification about new alerts in group
  group_interval: 10s
  
  # Wait time before sending notification about resolved alerts
  repeat_interval: 12h

  # Child routes with specific matchers
  routes:
    # Critical alerts - immediate notification via PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 30m

    # Warning alerts - Slack notification only
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 2h

    # Business alerts - dedicated channel
    - match:
        category: business
      receiver: 'business-alerts'
      group_wait: 1m
      group_interval: 30m
      repeat_interval: 6h

    # Database alerts - DBA team
    - match_re:
        category: database|cache
      receiver: 'database-team'
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 1h

    # Infrastructure alerts - DevOps team
    - match:
        category: infrastructure
      receiver: 'devops-team'
      group_wait: 1m
      group_interval: 10m
      repeat_interval: 2h

# Alert receivers configuration
receivers:
  # Default receiver
  - name: 'default-receiver'
    slack_configs:
      - channel: '#saas-alerts'
        title: '🔔 Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Severity:* {{ .Labels.severity }}
            *Service:* {{ .Labels.service }}
            *Description:* {{ .Annotations.description }}
            *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

  # Critical alerts receiver
  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_INTEGRATION_KEY}'
        severity: 'critical'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.service }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
    slack_configs:
      - channel: '#saas-critical'
        username: 'AlertManager'
        icon_emoji: ':rotating_light:'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          <!channel>
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Service:* {{ .Labels.service }}
            *Instance:* {{ .Labels.instance }}
            *Description:* {{ .Annotations.description }}
            *Runbook:* {{ .Annotations.runbook_url }}
            *Started:* {{ .StartsAt }}
          {{ end }}
        send_resolved: true
        color: 'danger'
    webhook_configs:
      - url: '${WEBHOOK_URL}/critical'
        send_resolved: true

  # Warning alerts receiver
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#saas-warnings'
        username: 'AlertManager'
        icon_emoji: ':warning:'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Service:* {{ .Labels.service }}
            *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true
        color: 'warning'

  # Business alerts receiver
  - name: 'business-alerts'
    slack_configs:
      - channel: '#saas-business'
        username: 'Business Metrics'
        icon_emoji: ':chart_with_upwards_trend:'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Category:* {{ .Labels.category }}
            *Description:* {{ .Annotations.description }}
            *Value:* {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
        color: 'warning'
    email_configs:
      - to: 'business@aviladevops.com.br'
        from: 'alerts@aviladevops.com.br'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${SMTP_USER}'
        auth_password: '${SMTP_PASSWORD}'
        headers:
          subject: '[Business Alert] {{ .GroupLabels.alertname }}'

  # Database team receiver
  - name: 'database-team'
    slack_configs:
      - channel: '#saas-database'
        username: 'Database Monitor'
        icon_emoji: ':database:'
        title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Service:* {{ .Labels.service }}
            *Instance:* {{ .Labels.instance }}
            *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true
    email_configs:
      - to: 'dba@aviladevops.com.br'
        from: 'alerts@aviladevops.com.br'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${SMTP_USER}'
        auth_password: '${SMTP_PASSWORD}'

  # DevOps team receiver
  - name: 'devops-team'
    slack_configs:
      - channel: '#saas-infrastructure'
        username: 'Infrastructure Monitor'
        icon_emoji: ':gear:'
        title: '⚙️ Infrastructure Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Instance:* {{ .Labels.instance }}
            *Description:* {{ .Annotations.description }}
            *Value:* {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
    email_configs:
      - to: 'devops@aviladevops.com.br'
        from: 'alerts@aviladevops.com.br'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${SMTP_USER}'
        auth_password: '${SMTP_PASSWORD}'

# Inhibition rules - prevent notification floods
inhibit_rules:
  # Inhibit warning if critical is firing for same alert
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

  # Inhibit service alerts if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service', 'instance']

  # Inhibit database connection alerts if database is down
  - source_match:
      alertname: 'PostgreSQLDown'
    target_match_re:
      alertname: 'PostgreSQL.*'
    equal: ['instance']

  # Inhibit Redis connection alerts if Redis is down
  - source_match:
      alertname: 'RedisDown'
    target_match_re:
      alertname: 'Redis.*'
    equal: ['instance']
