# Grafana Datasources Provisioning
# Automatically configure datasources on Grafana startup

apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
    version: 1

  # Elasticsearch datasource for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    editable: true
    jsonData:
      esVersion: "8.8.0"
      timeField: "@timestamp"
      interval: Daily
      logMessageField: message
      logLevelField: level
    version: 1

  # Jaeger datasource for tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'Elasticsearch'
        tags: ['trace_id', 'span_id']
        mappedTags: [{ key: 'service', value: 'service.name' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
    version: 1

  # PostgreSQL datasource for direct database queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: aviladevops_saas
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    version: 1
