name: Deploy All Projects to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-landing-page:
    uses: ./LANDING-PAGE/.github/workflows/deploy.yml@main
    secrets: inherit

  deploy-sistema:
    uses: ./sistema/.github/workflows/deploy.yml@main
    secrets: inherit

  deploy-fiscal:
    uses: ./fiscal/.github/workflows/deploy.yml@main
    secrets: inherit

  deploy-clinica:
    uses: ./clinica/.github/workflows/deploy.yml@main
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-landing-page, deploy-sistema, deploy-fiscal, deploy-clinica]
    if: always()

    steps:
    - name: Notify deployment status
      run: |
        echo "All projects deployment completed!"
        echo "Status: ${{ needs.deploy-landing-page.result }}"
